name: CI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/vagran/pulse-build:latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [cc, gcc, clang]
        build_type: [Debug, Release]
        validator: [valgrind, sanitize]

    name: Unit tests ${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.validator }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set build directory
        run: echo "BUILD_DIR=build/${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.validator }}" >> $GITHUB_ENV

      - name: Select compiler
        run: |
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            echo "CC=/usr/bin/gcc" >> $GITHUB_ENV
            echo "CXX=/usr/bin/g++" >> $GITHUB_ENV
          elif [ "${{ matrix.compiler }}" = "clang" ]; then
            echo "CC=/usr/bin/clang" >> $GITHUB_ENV
            echo "CXX=/usr/bin/clang++" >> $GITHUB_ENV
          fi

      - name: Select validator
        run: |
          if [ "${{ matrix.validator }}" = "sanitize" ]; then
            echo "SANITIZE=ON" >> $GITHUB_ENV
          elif [ "${{ matrix.compiler }}" = "clang" ]; then
            echo "SANITIZE=OFF" >> $GITHUB_ENV
          fi

      - name: Configure
        run: >
          cmake -S test -B $BUILD_DIR
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DSANITIZE=$SANITIZE

      - name: Build
        run: cmake --build $BUILD_DIR --target pulse_test

      - name: Run unit tests
        run: |
          if [ "${{ matrix.validator }}" = "valgrind" ]; then
            valgrind --leak-check=full $BUILD_DIR/pulse_test
          else
            $BUILD_DIR/pulse_test
          fi

  build-examples:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/vagran/pulse-build:latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release, MinSizeRel]
        example: [stm32f103-blue-pill, nrf52840]

    name: Examples cross-compilation ${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.example }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set build directory
        run: echo "BUILD_DIR=build/${{ matrix.example }}-${{ matrix.compiler }}-${{ matrix.build_type }}" >> $GITHUB_ENV

      - name: Configure
        run: >
          cmake -S examples/${{ matrix.example }} -B $BUILD_DIR
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_TOOLCHAIN_FILE=$PWD/examples/arm-${{ matrix.compiler }}-toolchain.cmake

      - name: Build
        run: cmake --build $BUILD_DIR --target all
